name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose the Node.js version that matches your development environment

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npx umi build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to 